<?php

use Drupal\Component\Plugin\PluginManagerInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\entity_access_policies\LockInterface;
use Drupal\entity_access_policies\PolicyInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_access_records().
 *
 * Shims Entity Access Policies in for just nodes. Later, the policies code
 * can be refactored into an entity type agnostic system.
 */
function entity_access_policies_node_access_records(NodeInterface $node) {
  $policy_manager = Drupal::service('plugin.manager.entity_access_policy');
  /* @var \Drupal\Component\Plugin\PluginManagerInterface $policy_manager */

  $access_records = [];
  $definitions = $policy_manager->getDefinitions();
  foreach (array_keys($definitions) as $policy_id) {
    $policy = $policy_manager->createInstance($policy_id);

    if ($policy->applies($node)) {
      $locks = $policy->getLocks($node);
      /* @var \Drupal\entity_access_policies\LockInterface[] $locks */
      foreach ($locks as $lock) {
        $access_records[] = _entity_access_policies_lock_to_grant($policy_id, $lock);
      }
    }
  }

  return $access_records;
}

/**
 * Implements hook_node_access_records().
 *
 * Shims Entity Access Policies in for just nodes. Later, the policies code
 * can be refactored into an entity type agnostic system.
 */
function entity_access_policies_node_grants(AccountInterface $account, $op) {
  $policy_manager = Drupal::service('plugin.manager.entity_access_policy');
  /* @var \Drupal\Component\Plugin\PluginManagerInterface $policy_manager */

  $grants = [];
  $definitions = $policy_manager->getDefinitions();
  foreach (array_keys($definitions) as $policy_id) {
    $policy = $policy_manager->createInstance($policy_id);

    $keys = $policy->getKeys($account);
    foreach ($keys as $key) {
      $grants[] = $policy_id . ':' . $key;
    }
  }

  return ['entity_access_policies' => $grants];
}

/**
 * Simple helper function which maps Locks to node access record arrays.
 *
 * This is only necessary until the node_access system is replaced with a
 * more generic entity access system.
 */
function _entity_access_policies_lock_to_grant($policy_id, LockInterface $lock) {
  $grant = [
    'realm' => 'entity_access_policies',
    'gid' => $policy_id . ':' . $lock->id(),
    'langcode' => $lock->getLanguage(),
  ];

  foreach ($lock->getOperations() as $operation) {
    $grant['grant_' . $operation] = 1;
  }

  return $grant;
}
